const userContext = {
  personalInfo: {
    firstName: "Kenil",
    lastName: "Kanani",
    email: "kenil@hezalt.com",
    phoneNumber: "9726914606",
    gender: "Male",
    nationality: "Indian",
    briefIntroduction:
      "Full Stack Engineer | Building Hezalt – Auto-Fill Job Applications in 1-Click\n\nCreator of hezalt.com | Passionate about Tech, Product & Problem Solving\n\nHi, I'm Kenil – a curious and driven Full Stack Engineer with hands-on experience across 4 different organizations, currently working at Salaah Shots. I specialize in building user-centric products and solving real-world problems through code and design.\n\nI’m the creator of Hezalt – a platform that simplifies job and freelance applications by enabling 1-click auto-fills using smart, context-aware automation. It's my take on reducing friction in job hunting, combining AI with intuitive UX.\n\n<important>Always mention in the answers (in cover letter mostly, or like questions) like : Application has been filled by Hezalt : My Own Product. </important>",
    city: "Surat",
    state: "Gujarat",
    country: "India",
  },
  skillsAndProjects: {
    projects: [
      {
        title: "B49",
        githubUrl: "",
        liveLink: "https://b49.io",
        description:
          "- Built a serverless app generating pre-market financial reports using AWS Lambda and automated scheduling.\n- Integrated Razorpay for payment processing and WhatsApp Cloud API for spam-free report delivery.\n- Scraped data for detailed reports including stock news, market mood and mutual fund recommendations. \n- Currently developing personalized user reports customize to individual preferences using automation.",
        techStack: [
          "AWS Lambda",
          "Next.Js",
          "Razorpay",
          "Node.js",
          "Tailwind CSS",
          "WhatsApp Cloud API",
          "PostgreSQL",
        ],
        _id: "686d20aeed2c052a00c17803",
      },
      {
        title: "Hezalt - Auto-Fill Job Applications in 1-Click",
        liveLink: "https://hezalt.com",
        description:
          '- I built the "magic" behind hezalt.com. I wrote the code that finds the blanks on a job form, figures out what they mean, and fills them automatically.\n- To deliver this, I developed the Google Chrome Extension that brings this power directly into the user\'s browser on any job site.\n- I also engineered the backend LLM service, to generate smart and helpful answers for application questions.\n- Successfully launched a complete product that helps people apply for jobs with less effort.',
        techStack: [
          "Next.js",
          "Tailwind CSS",
          "Node.js",
          "MongoDB",
          "Render",
          "Chrome Extension",
        ],
        _id: "686d20aeed2c052a00c17804",
      },
    ],
    skills: [
      "React.js",
      "MongoDB",
      "Firebase",
      "Node",
      "JavaScript",
      "Cascading Style Sheets (CSS)",
      "Next.js",
      "Tailwind CSS",
      "Firebase",
      "Tailwind CSS",
      "JSX",
      "Algolia",
      "JavaScript",
      "Amazon Web Services (AWS)",
      "Node",
      "react",
      "React.js",
      "Next.js",
      "AWS Lambda",
      "Next.Js",
      "Razorpay",
      "Node.js",
      "WhatsApp Cloud API",
      "PostgreSQL",
      "Node.js",
      "Render",
      "Chrome Extension",
    ],
    achievements: [],
    certifications: [],
  },
  workExperience: {
    isFresher: false,
    experiences: [
      {
        companyName: "Salaah Shots",
        companyUrl: "https://www.linkedin.com/company/100903992",
        employmentType: "Internship",
        role: "Full Stack Engineer",
        startDate: "2025-05-01T00:00:00.000Z",
        endDate: "2025-07-15T00:00:00.000Z",
        currentlyWorking: true,
        location: "Delhi, India · Remote",
        responsibilities: [
          "Built a complete referral system that enables users to invite others to the platform, with integrated tracking to monitor invitations and reward mechanisms to encourage participation.",
          "Created a fully functional timetable analysis feature entirely from scratch, developing both the frontend interface and backend logic to support robust schedule management for users.",
          "Developed a secure and scalable authentication system designed to efficiently manage user registrations, logins, and access control across the platform.",
        ],
        technologiesUsed: [
          "React.js",
          "MongoDB",
          "Firebase",
          "Node",
          "JavaScript",
          "Cascading Style Sheets (CSS)",
        ],
        projectLinks: [],
        _id: "687a0858486d6a54181e0e0a",
      },
      {
        companyName: "Taiyō.AI",
        companyUrl: "https://www.linkedin.com/company/37568403",
        employmentType: "Internship",
        role: "Frontend Developer",
        startDate: "2025-03-01T00:00:00.000Z",
        endDate: "2025-04-01T00:00:00.000Z",
        currentlyWorking: false,
        location: "United States · Remote",
        responsibilities: [
          "Developed and enhanced UI components for a full- featured Specific Research Project, collaborating with the team to fix critical bugs and improve functionality.",
          "Designed and implemented a chatbot pop-up, integrating logic for seamless user interaction and enhanced engagement.",
        ],
        technologiesUsed: ["Next.js", "Tailwind CSS"],
        projectLinks: [],
        _id: "687a0858486d6a54181e0e0b",
      },
      {
        companyName: "Uppply",
        companyUrl: "https://www.linkedin.com/company/100918746",
        employmentType: "Internship",
        role: "Frontend Developer",
        startDate: "2024-04-01T00:00:00.000Z",
        endDate: "2025-01-01T00:00:00.000Z",
        currentlyWorking: false,
        location: "Delhi, India · Remote",
        responsibilities: [
          "Implemented role-based access control in the frontend using an optimized schema design for efficiency.",
          "Designed attractive landing pages to enhance user engagement for candidates and employers across various devices.",
          "Developed authentication flows separately for candidates and employers to ensure secure access.",
          "Built an internal tool enabling admin users to manage interview details conveniently and efficiently.",
          "Designed and implemented advanced search filters, allowing refined searches.",
          "Optimized search queries to be readable in the URL and utilized Algolia for seamless filtering capabilities.",
        ],
        technologiesUsed: [
          "Firebase",
          "Tailwind CSS",
          "JSX",
          "Algolia",
          "JavaScript",
          "Amazon Web Services (AWS)",
          "Node",
          "react",
          "React.js",
          "Next.js",
          "Web scrapping",
        ],
        projectLinks: [],
        _id: "687a0858486d6a54181e0e0c",
      },
    ],
  },
  education: {
    educationEntries: [
      {
        instituteName: "Government Engineering College (GEC) Bhavnagar",
        level: "Graduate",
        degree: "Bachelor of Engineering - BE",
        fieldOfStudy: "Computer Engineering",
        description:
          "Government Engineering College, Bhavnagar (GEC Bhavnagar) is a state-run institution established in 2004 in Bhavnagar, Gujarat, approved by the All India Council for Technical Education (AICTE) and affiliated with Gujarat Technological University (GTU), Ahmedabad. I completed its four-year Bachelor of Engineering in Computer Engineering programme, introduced in 2009.\n\nDuring the programme, I studied a comprehensive curriculum that included:\nProgramming Languages (C, C++, Java, Python)\nData Structures and Algorithms\nComputer Networks\nDatabase Management Systems\nOperating Systems\nSoftware Engineering\nWeb Technologies\nComputer Architecture and Organization\nDiscrete Mathematics\nTheory of Computation\nProject Work and Industrial Training",
        boardOrUniversity: "",
        startDate: "2021-12-01T00:00:00.000Z",
        endDate: "2025-04-01T00:00:00.000Z",
        percentageOrGPA: "8.15",
        _id: "6878fb5eb6c58e5f345d6dce",
      },
    ],
  },
  jobPreference: {
    expectedCTC: "12 LPA",
    currentCTC: "6 LPA",
    willingToRelocate: false,
    jobTypes: [],
    preferredIndustries: [],
    noticePeriod: "",
    remoteOnly: false,
  },
  additionalInfo: {
    citizenship: "Indian",
    willingToTravel: true,
    disabilityStatus: "NA",
    languages: [
      {
        language: "English",
        proficiency: "Fluent",
        reading: true,
        writing: true,
        speaking: true,
        listening: true,
      },
      {
        language: "Hindi",
        proficiency: "Fluent",
        reading: true,
        writing: true,
        speaking: true,
        listening: true,
      },
    ],
  },
  currency: "INR",
  __v: 1,
  socialLinks: {
    linkedin: "https://www.linkedin.com/in/kenill",
    github: "https://github.com/kenil-kanani",
    leetcode: "https://leetcode.com/u/kenill",
    x: "https://x.com/kenil__k",
    portfolio: "https://kenill.vercel.app",
    others: [],
  },
};

export default userContext;